/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FitnessId = IDL.Text;
export const FitnessListing = IDL.Record({
  'id' : FitnessId,
  'duration' : IDL.Float64,
  'cost' : IDL.Float64,
  'name' : IDL.Text,
  'typeOfClass' : IDL.Text,
  'location' : IDL.Text,
  'online' : IDL.Bool,
});
export const MembershipId = IDL.Text;
export const MembershipPlan = IDL.Record({
  'id' : MembershipId,
  'duration' : IDL.Float64,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Float64,
});
export const Provider = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'specialization' : IDL.Text,
  'location' : IDL.Text,
  'online' : IDL.Bool,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PatientId = IDL.Principal;
export const PatientProfile = IDL.Record({
  'id' : PatientId,
  'age' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'preferences' : IDL.Text,
  'isVIP' : IDL.Bool,
});
export const ConsultationId = IDL.Text;
export const ConsultationStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Time = IDL.Int;
export const ProviderId = IDL.Principal;
export const Consultation = IDL.Record({
  'id' : ConsultationId,
  'status' : ConsultationStatus,
  'patientId' : PatientId,
  'time' : Time,
  'modality' : IDL.Text,
  'notes' : IDL.Text,
  'providerId' : ProviderId,
});
export const ConsultationRequest = IDL.Record({
  'patientId' : PatientId,
  'time' : Time,
  'modality' : IDL.Text,
  'notes' : IDL.Text,
  'providerId' : ProviderId,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFitnessListing' : IDL.Func([FitnessListing], [], []),
  'addMembershipPlan' : IDL.Func([MembershipPlan], [], []),
  'addProvider' : IDL.Func([Provider], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteFitnessListing' : IDL.Func([FitnessId], [], []),
  'deleteMembershipPlan' : IDL.Func([MembershipId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(PatientProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConsultations' : IDL.Func([], [IDL.Vec(Consultation)], ['query']),
  'getPatientProfile' : IDL.Func([], [PatientProfile], ['query']),
  'getProvider' : IDL.Func([ProviderId], [Provider], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PatientProfile)],
      ['query'],
    ),
  'getVIPStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listFitnessListings' : IDL.Func([], [IDL.Vec(FitnessListing)], ['query']),
  'listMembershipPlans' : IDL.Func([], [IDL.Vec(MembershipPlan)], ['query']),
  'listProviders' : IDL.Func([], [IDL.Vec(Provider)], ['query']),
  'requestConsultation' : IDL.Func([ConsultationRequest], [ConsultationId], []),
  'saveCallerUserProfile' : IDL.Func([PatientProfile], [], []),
  'savePatientProfile' : IDL.Func([PatientProfile], [], []),
  'setVIPStatus' : IDL.Func([PatientId, IDL.Bool], [], []),
  'updateConsultationStatus' : IDL.Func(
      [ConsultationId, ConsultationStatus],
      [],
      [],
    ),
  'updateFitnessListing' : IDL.Func([FitnessListing], [], []),
  'updateMembershipPlan' : IDL.Func([MembershipPlan], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FitnessId = IDL.Text;
  const FitnessListing = IDL.Record({
    'id' : FitnessId,
    'duration' : IDL.Float64,
    'cost' : IDL.Float64,
    'name' : IDL.Text,
    'typeOfClass' : IDL.Text,
    'location' : IDL.Text,
    'online' : IDL.Bool,
  });
  const MembershipId = IDL.Text;
  const MembershipPlan = IDL.Record({
    'id' : MembershipId,
    'duration' : IDL.Float64,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Float64,
  });
  const Provider = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'specialization' : IDL.Text,
    'location' : IDL.Text,
    'online' : IDL.Bool,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PatientId = IDL.Principal;
  const PatientProfile = IDL.Record({
    'id' : PatientId,
    'age' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'preferences' : IDL.Text,
    'isVIP' : IDL.Bool,
  });
  const ConsultationId = IDL.Text;
  const ConsultationStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Time = IDL.Int;
  const ProviderId = IDL.Principal;
  const Consultation = IDL.Record({
    'id' : ConsultationId,
    'status' : ConsultationStatus,
    'patientId' : PatientId,
    'time' : Time,
    'modality' : IDL.Text,
    'notes' : IDL.Text,
    'providerId' : ProviderId,
  });
  const ConsultationRequest = IDL.Record({
    'patientId' : PatientId,
    'time' : Time,
    'modality' : IDL.Text,
    'notes' : IDL.Text,
    'providerId' : ProviderId,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFitnessListing' : IDL.Func([FitnessListing], [], []),
    'addMembershipPlan' : IDL.Func([MembershipPlan], [], []),
    'addProvider' : IDL.Func([Provider], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteFitnessListing' : IDL.Func([FitnessId], [], []),
    'deleteMembershipPlan' : IDL.Func([MembershipId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(PatientProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConsultations' : IDL.Func([], [IDL.Vec(Consultation)], ['query']),
    'getPatientProfile' : IDL.Func([], [PatientProfile], ['query']),
    'getProvider' : IDL.Func([ProviderId], [Provider], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PatientProfile)],
        ['query'],
      ),
    'getVIPStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listFitnessListings' : IDL.Func([], [IDL.Vec(FitnessListing)], ['query']),
    'listMembershipPlans' : IDL.Func([], [IDL.Vec(MembershipPlan)], ['query']),
    'listProviders' : IDL.Func([], [IDL.Vec(Provider)], ['query']),
    'requestConsultation' : IDL.Func(
        [ConsultationRequest],
        [ConsultationId],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([PatientProfile], [], []),
    'savePatientProfile' : IDL.Func([PatientProfile], [], []),
    'setVIPStatus' : IDL.Func([PatientId, IDL.Bool], [], []),
    'updateConsultationStatus' : IDL.Func(
        [ConsultationId, ConsultationStatus],
        [],
        [],
      ),
    'updateFitnessListing' : IDL.Func([FitnessListing], [], []),
    'updateMembershipPlan' : IDL.Func([MembershipPlan], [], []),
  });
};

export const init = ({ IDL }) => { return []; };