/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Consultation {
  'id' : ConsultationId,
  'status' : ConsultationStatus,
  'patientId' : PatientId,
  'time' : Time,
  'modality' : string,
  'notes' : string,
  'providerId' : ProviderId,
}
export type ConsultationId = string;
export interface ConsultationRequest {
  'patientId' : PatientId,
  'time' : Time,
  'modality' : string,
  'notes' : string,
  'providerId' : ProviderId,
}
export type ConsultationStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export type FitnessId = string;
export interface FitnessListing {
  'id' : FitnessId,
  'duration' : number,
  'cost' : number,
  'name' : string,
  'typeOfClass' : string,
  'location' : string,
  'online' : boolean,
}
export type MembershipId = string;
export interface MembershipPlan {
  'id' : MembershipId,
  'duration' : number,
  'name' : string,
  'description' : string,
  'price' : number,
}
export type PatientId = Principal;
export interface PatientProfile {
  'id' : PatientId,
  'age' : bigint,
  'name' : string,
  'description' : string,
  'preferences' : string,
  'isVIP' : boolean,
}
export interface Provider {
  'id' : Principal,
  'name' : string,
  'specialization' : string,
  'location' : string,
  'online' : boolean,
}
export type ProviderId = Principal;
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFitnessListing' : ActorMethod<[FitnessListing], undefined>,
  'addMembershipPlan' : ActorMethod<[MembershipPlan], undefined>,
  'addProvider' : ActorMethod<[Provider], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteFitnessListing' : ActorMethod<[FitnessId], undefined>,
  'deleteMembershipPlan' : ActorMethod<[MembershipId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [PatientProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConsultations' : ActorMethod<[], Array<Consultation>>,
  'getPatientProfile' : ActorMethod<[], PatientProfile>,
  'getProvider' : ActorMethod<[ProviderId], Provider>,
  'getUserProfile' : ActorMethod<[Principal], [] | [PatientProfile]>,
  'getVIPStatus' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listFitnessListings' : ActorMethod<[], Array<FitnessListing>>,
  'listMembershipPlans' : ActorMethod<[], Array<MembershipPlan>>,
  'listProviders' : ActorMethod<[], Array<Provider>>,
  'requestConsultation' : ActorMethod<[ConsultationRequest], ConsultationId>,
  'saveCallerUserProfile' : ActorMethod<[PatientProfile], undefined>,
  'savePatientProfile' : ActorMethod<[PatientProfile], undefined>,
  'setVIPStatus' : ActorMethod<[PatientId, boolean], undefined>,
  'updateConsultationStatus' : ActorMethod<
    [ConsultationId, ConsultationStatus],
    undefined
  >,
  'updateFitnessListing' : ActorMethod<[FitnessListing], undefined>,
  'updateMembershipPlan' : ActorMethod<[MembershipPlan], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];