/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export type MembershipId = string;
export interface ConsultationRequest {
    patientId: PatientId;
    time: Time;
    modality: string;
    notes: string;
    providerId: ProviderId;
}
export type FitnessId = string;
export type ConsultationId = string;
export type PatientId = Principal;
export type ProviderId = Principal;
export interface PatientProfile {
    id: PatientId;
    age: bigint;
    name: string;
    description: string;
    preferences: string;
    isVIP: boolean;
}
export interface MembershipPlan {
    id: MembershipId;
    duration: number;
    name: string;
    description: string;
    price: number;
}
export interface FitnessListing {
    id: FitnessId;
    duration: number;
    cost: number;
    name: string;
    typeOfClass: string;
    location: string;
    online: boolean;
}
export interface Consultation {
    id: ConsultationId;
    status: ConsultationStatus;
    patientId: PatientId;
    time: Time;
    modality: string;
    notes: string;
    providerId: ProviderId;
}
export interface Provider {
    id: Principal;
    name: string;
    specialization: string;
    location: string;
    online: boolean;
}
export enum ConsultationStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    confirmed = "confirmed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addFitnessListing(listing: FitnessListing): Promise<void>;
    addMembershipPlan(plan: MembershipPlan): Promise<void>;
    addProvider(profile: Provider): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteFitnessListing(id: FitnessId): Promise<void>;
    deleteMembershipPlan(id: MembershipId): Promise<void>;
    getCallerUserProfile(): Promise<PatientProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getConsultations(): Promise<Array<Consultation>>;
    getPatientProfile(): Promise<PatientProfile>;
    getProvider(id: ProviderId): Promise<Provider>;
    getUserProfile(user: Principal): Promise<PatientProfile | null>;
    getVIPStatus(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    listFitnessListings(): Promise<Array<FitnessListing>>;
    listMembershipPlans(): Promise<Array<MembershipPlan>>;
    listProviders(): Promise<Array<Provider>>;
    requestConsultation(request: ConsultationRequest): Promise<ConsultationId>;
    saveCallerUserProfile(profile: PatientProfile): Promise<void>;
    savePatientProfile(profile: PatientProfile): Promise<void>;
    setVIPStatus(patientId: PatientId, isVIP: boolean): Promise<void>;
    updateConsultationStatus(consultationId: ConsultationId, newStatus: ConsultationStatus): Promise<void>;
    updateFitnessListing(listing: FitnessListing): Promise<void>;
    updateMembershipPlan(plan: MembershipPlan): Promise<void>;
}
import type { Consultation as _Consultation, ConsultationId as _ConsultationId, ConsultationStatus as _ConsultationStatus, PatientId as _PatientId, PatientProfile as _PatientProfile, ProviderId as _ProviderId, Time as _Time, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addFitnessListing(arg0: FitnessListing): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFitnessListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFitnessListing(arg0);
            return result;
        }
    }
    async addMembershipPlan(arg0: MembershipPlan): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMembershipPlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMembershipPlan(arg0);
            return result;
        }
    }
    async addProvider(arg0: Provider): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProvider(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProvider(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteFitnessListing(arg0: FitnessId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFitnessListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFitnessListing(arg0);
            return result;
        }
    }
    async deleteMembershipPlan(arg0: MembershipId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMembershipPlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMembershipPlan(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<PatientProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConsultations(): Promise<Array<Consultation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConsultations();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConsultations();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPatientProfile(): Promise<PatientProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatientProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatientProfile();
            return result;
        }
    }
    async getProvider(arg0: ProviderId): Promise<Provider> {
        if (this.processError) {
            try {
                const result = await this.actor.getProvider(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProvider(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<PatientProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVIPStatus(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getVIPStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVIPStatus();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listFitnessListings(): Promise<Array<FitnessListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFitnessListings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFitnessListings();
            return result;
        }
    }
    async listMembershipPlans(): Promise<Array<MembershipPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMembershipPlans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMembershipPlans();
            return result;
        }
    }
    async listProviders(): Promise<Array<Provider>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProviders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProviders();
            return result;
        }
    }
    async requestConsultation(arg0: ConsultationRequest): Promise<ConsultationId> {
        if (this.processError) {
            try {
                const result = await this.actor.requestConsultation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestConsultation(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: PatientProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async savePatientProfile(arg0: PatientProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePatientProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePatientProfile(arg0);
            return result;
        }
    }
    async setVIPStatus(arg0: PatientId, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setVIPStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setVIPStatus(arg0, arg1);
            return result;
        }
    }
    async updateConsultationStatus(arg0: ConsultationId, arg1: ConsultationStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateConsultationStatus(arg0, to_candid_ConsultationStatus_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateConsultationStatus(arg0, to_candid_ConsultationStatus_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateFitnessListing(arg0: FitnessListing): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFitnessListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFitnessListing(arg0);
            return result;
        }
    }
    async updateMembershipPlan(arg0: MembershipPlan): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMembershipPlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMembershipPlan(arg0);
            return result;
        }
    }
}
function from_candid_ConsultationStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConsultationStatus): ConsultationStatus {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Consultation_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Consultation): Consultation {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PatientProfile]): PatientProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ConsultationId;
    status: _ConsultationStatus;
    patientId: _PatientId;
    time: _Time;
    modality: string;
    notes: string;
    providerId: _ProviderId;
}): {
    id: ConsultationId;
    status: ConsultationStatus;
    patientId: PatientId;
    time: Time;
    modality: string;
    notes: string;
    providerId: ProviderId;
} {
    return {
        id: value.id,
        status: from_candid_ConsultationStatus_n9(_uploadFile, _downloadFile, value.status),
        patientId: value.patientId,
        time: value.time,
        modality: value.modality,
        notes: value.notes,
        providerId: value.providerId
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
}): ConsultationStatus {
    return "cancelled" in value ? ConsultationStatus.cancelled : "pending" in value ? ConsultationStatus.pending : "completed" in value ? ConsultationStatus.completed : "confirmed" in value ? ConsultationStatus.confirmed : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Consultation>): Array<Consultation> {
    return value.map((x)=>from_candid_Consultation_n7(_uploadFile, _downloadFile, x));
}
function to_candid_ConsultationStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConsultationStatus): _ConsultationStatus {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConsultationStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
} {
    return value == ConsultationStatus.cancelled ? {
        cancelled: null
    } : value == ConsultationStatus.pending ? {
        pending: null
    } : value == ConsultationStatus.completed ? {
        completed: null
    } : value == ConsultationStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
